#!/bin/sh
# replace string literals with it's human readable values
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0002/TCONST_pMem/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0003/TCONST_lamptext/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0004/TCONST_settings/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0005/TCONST_set_effect/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0006/TCONST_eff_sel/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0007/TCONST_eff_fav/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0008/TCONST_encoder/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0009/TCONST_copy/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000A/TCONST_del_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000B/TCONST_makeidx/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000C/TCONST_set_enc/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000D/TCONST_black/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000E/TCONST_AUX/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_000F/TCONST_effects_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0010/TCONST_effListConf/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0012/TCONST_bright/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0013/TCONST_speed/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0014/TCONST_scale/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0016/TCONST_effListMain/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0017/TCONST_nofade/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0018/TCONST_GlobBRI/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0019/TCONST_flags/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001A/TCONST_ONflag/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001B/TCONST_Demo/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001C/TCONST_GBR/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001D/TCONST_Events/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001E/TCONST_Mic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_001F/TCONST_Btn/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0020/TCONST_show_flags/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0021/TCONST_mode/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0022/TCONST_eff_prev/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0023/TCONST_eff_next/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0024/TCONST__708090/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0025/TCONST__5f9ea0/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0026/TCONST_DTimer/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0027/TCONST_OTA/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0028/TCONST_lamp_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0029/TCONST_edit_lamp_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002A/TCONST_fileName/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002B/TCONST__backup_idx/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002C/TCONST__backup_idx_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002D/TCONST_load/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002E/TCONST_save/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_002F/TCONST_ds18b20/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0030/TCONST_add_lamp_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0031/TCONST__backup_glb_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0032/TCONST__backup_evn_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0033/TCONST__backup_btn_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0034/TCONST_textsend/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0035/TCONST_msg/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0036/TCONST_txtColor/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0037/TCONST_settings_mic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0038/TCONST_set_mic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0039/TCONST_micScale/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003A/TCONST_micNoise/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003B/TCONST_micnRdcLvl/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003C/TCONST_mic_cal/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003D/TCONST_settings_wifi/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003E/TCONST_pTemp/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_003F/TCONST_EncVG/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0040/TCONST_EncVGCol/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0041/TCONST_wcpass/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0042/TCONST_encTxtCol/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0043/TCONST_encTxtDel/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0044/TCONST_streaming/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0045/TCONST_set_mqtt/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0046/TCONST_isStreamOn/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0047/TCONST_stream_type/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0048/TCONST_isShowOff/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0049/TCONST_direct/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004A/TCONST_mapping/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004B/TCONST_set_other/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004C/TCONST_MIRR_H/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004D/TCONST_MIRR_V/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004E/TCONST_isFaderON/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_004F/TCONST_DRand/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0050/TCONST_effSort/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0051/TCONST_txtSpeed/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0052/TCONST_txtOf/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0053/TCONST_spdcf/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0054/TCONST_ny_period/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0055/TCONST_ny_unix/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0056/TCONST_isPlayTime/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_005B/TCONST_blue/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_005C/TCONST_show_event/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_005D/TCONST_event_conf/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_005E/TCONST_eventList/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_005F/TCONST_edit/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0060/TCONST_enabled/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0061/TCONST_d1/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0062/TCONST_d2/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0063/TCONST_d3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0064/TCONST_d4/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0065/TCONST_d5/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0066/TCONST_d6/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0067/TCONST_d7/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0068/TCONST_evList/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0069/TCONST_repeat/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006A/TCONST_stopat/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006B/TCONST_tmEvent/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006C/TCONST_set_event/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006D/TCONST_show_button/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006E/TCONST_butt_conf/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_006F/TCONST_buttList/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0070/TCONST_on/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0071/TCONST_hold/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0072/TCONST_onetime/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0073/TCONST_clicks/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0074/TCONST_bactList/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0075/TCONST_set_butt/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0076/TCONST_show_butt/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0077/TCONST_Universe/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0079/TCONST_show_mic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_007A/TCONST_show_other/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_007C/TCONST__ffffff/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_007D/TCONST_1609459200/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_007E/TCONST_main/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_007F/TCONST_dynCtrl_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0080/TCONST_STA/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0081/TCONST__tmpqlist_tmp/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0085/TCONST__tmplist_tmp/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_008B/TCONST_embui_pub_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_008C/TCONST_pin/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_008D/TCONST_act/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_008E/TCONST_isClearing/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_008F/TCONST_pUptime/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0090/TCONST_numInList/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0091/TCONST_effHasMic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0092/TCONST_effname/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0093/TCONST_set_opt_pass/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0094/TCONST_syslampFlags/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0095/TCONST_debug/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0096/TCONST_isShowSysMenu/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0097/TCONST_PINB/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0098/TCONST_CLmt/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_0099/TCONST_sysSettings/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009A/TCONST_ESPsysSettings/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009B/TCONST_PINMP3RX/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009C/TCONST_PINMP3TX/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009D/TCONST_isOnMP3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009E/TCONST_showName/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_009F/TCONST_show_mp3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A0/TCONST_set_mp3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A1/TCONST_settings_mp3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A2/TCONST_mp3volume/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A3/TCONST_playTime/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A4/TCONST_playName/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A5/TCONST_playEffect/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A6/TCONST_alarmSound/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A7/TCONST_eqSetings/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A8/TCONST_playMP3/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00A9/TCONST_mp3count/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AA/TCONST__demo/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AB/TCONST_soundfile/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AC/TCONST_embui_get_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AD/TCONST_state/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AE/TCONST_eff_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00AF/TCONST_limitAlarmVolume/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B0/TCONST_delfromlist/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B1/TCONST_delall/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B2/TCONST_delCfg/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B3/TCONST_orange/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B4/TCONST_gbright/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B5/TCONST_bparam/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B6/TCONST_delete/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B8/TCONST_opt_pass/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00B9/TCONST_text_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00BA/TCONST_edit_text_config/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00BB/TCONST_alarmP/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00BC/TCONST_alarmT/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00BD/TCONST_alarmPT/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C0/TCONST_mp3_p5/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C1/TCONST_mp3_n5/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C2/TCONST_pFS/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C3/TCONST_txtBfade/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C4/TCONST_drawbuff/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C8/TCONST_drawing/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00C9/TCONST_drawing_ctrl/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CA/TCONST_drawing_ctrl_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CB/TCONST_blabel/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CC/TCONST_height/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CD/TCONST_width/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CE/TCONST_pRSSI/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00CF/TCONST_fileName2/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D0/TCONST_control/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D1/TCONST_afS/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D2/TCONST_lV/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D3/TCONST_sT/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D5/TCONST_force/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D7/TCONST_tmBright/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D8/TCONST_tmBrightOn/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00D9/TCONST_tmBrightOff/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DA/TCONST_tm24/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DB/TCONST_tmZero/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DC/TCONST_drawClear/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DD/TCONST_Mode/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DE/TCONST_Time/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00DF/TCONST_Memory/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E0/TCONST_Uptime/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E1/TCONST_RSSI/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E2/TCONST_Ip/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E3/TCONST_Mac/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E4/TCONST_Host/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E5/TCONST_Version/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E6/TCONST_MQTTTopic/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E7/TCONST_embui_/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E8/TCONST_Normal/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00E9/TCONST_Alarm/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00EA/TCONST_Demo/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00EB/TCONST_RGB/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00EC/TCONST_White/g' {} +
find ./include/ ./src/ -type f -exec sed -i 's/TCONST_00ED/TCONST_Other/g' {} +