#pragma once
#include <string_view>

/** набор служебных текстовых констант (не для локализации)
 */
static const char* TCONST_1609459200 = "1609459200";
static const char* TCONST_act = "act";
static const char* TCONST_add_lamp_config = "add_lamp_config";
static const char* TCONST_afS = "afS";
static const char* TCONST_alarmPT = "alarmPT";
static const char* TCONST_alarmP = "alarmP";
static const char* TCONST_alarmSound = "alarmSound";
static const char* TCONST_alarmT = "alarmT";
static const char* TCONST_Alarm = "Alarm";
static const char* TCONST_AUX = "AUX";
static const char* TCONST_aux_gpio = "aux_gpio";             // AUX gpio
static const char* TCONST_aux_ll = "aux_ll";                 // AUX logic level
static const char* TCONST_bactList = "bactList";
static const char* TCONST_blabel = "blabel";
static const char* TCONST_bparam = "bparam";
static const char* TCONST_bright = "bright";
static const char* TCONST_brtScl = "brtScl";                 // brightness scale
static const char* TCONST_Btn = "Btn";
static const char* TCONST_buttList = "buttList";
static const char* TCONST_butt_conf = "butt_conf";
static const char* TCONST_clicks = "clicks";
static const char* TCONST_CLmt = "CLmt"; // лимит тока
static const char* TCONST_control = "control";
static const char* TCONST_copy = "copy";
static const char* TCONST_d1 = "d1";
static const char* TCONST_d2 = "d2";
static const char* TCONST_d3 = "d3";
static const char* TCONST_d4 = "d4";
static const char* TCONST_d5 = "d5";
static const char* TCONST_d6 = "d6";
static const char* TCONST_d7 = "d7";
static const char* TCONST_debug = "debug";
static const char* TCONST_delall = "delall";
static const char* TCONST_delCfg = "delCfg";
static const char* TCONST_delete = "delete";
static const char* TCONST_delfromlist = "delfromlist";
static const char* TCONST_del_ = "del*";
static const char* TCONST_Demo = "Demo";
static const char* TCONST_direct = "direct";
static const char* TCONST_DRand = "DRand";
static const char* TCONST_drawbuff = "drawbuff";
static const char* TCONST_drawClear = "drawClear";
static const char* TCONST_drawing = "drawing";
static const char* TCONST_draw_dat = "draw_dat";
static const char* TCONST_ds18b20 = "ds18b20";
static const char* TCONST_DTimer = "DTimer";
static const char* TCONST_dynCtrl = "dynCtrl";
static const char* TCONST_dynCtrl_ = "dynCtrl*";
static const char* TCONST_edit_lamp_config = "edit_lamp_config";
static const char* TCONST_edit_text_config = "edit_text_config";
static const char* TCONST_edit = "edit";
static const char* TCONST_eff_config = "eff_config";
static const char* TCONST_eff_fav = "eff_fav";
static const char* TCONST_eff_fulllist_json = "/eff_fulllist.json"; // a json serialized full list of effects and it's names for WebUI drop-down list on effects management page
static const char* TCONST_eff_index = "/eff_index.json";
static const char* TCONST_eff_list_json_tmp = "/eff_list.json.tmp"; // a json serialized list of effects and it's names for WebUI drop-down list
static const char* TCONST_eff_list_json = "/eff_list.json";         // a json serialized list of effects and it's names for WebUI drop-down list on main page
static const char* TCONST_eff_next = "eff_next";
static const char* TCONST_eff_prev = "eff_prev";
static const char* TCONST_eff_sel = "eff_sel";
static const char* TCONST_eff_ctrls = "eff_ctrls";
static const char* TCONST_effects_config = "effects_config";
static const char* TCONST_effects = "effects";
static const char* TCONST_effHasMic = "effHasMic";
static const char* TCONST_effListConf = "effListConf";
static const char* TCONST_eff_run = "effrun";                       // switch running effect to effect_#
static const char* TCONST_effname = "effname";
static const char* TCONST_effSort = "effSort";
static const char* TCONST_embui_get_ = "embui/get/";
static const char* TCONST_embui_pub_ = "embui/pub/";
static const char* TCONST_embui_ = "embui/";
static const char* TCONST_enabled = "enabled";
static const char* TCONST_encoder = "encoder";
static const char* TCONST_encTxtCol = "encTxtCol";
static const char* TCONST_encTxtDel = "encTxtDel";
static const char* TCONST_EncVGCol = "EncVGCol";
static const char* TCONST_EncVG = "EncVG";
static const char* TCONST_eqSetings = "eqSetings";
static const char* TCONST_event = "event";
static const char* TCONST_eventList = "eventList";
static const char* TCONST_Events = "Events";
static const char* TCONST_event_conf = "event_conf";
static const char* TCONST_evList = "evList";
static const char* TCONST_f_restore_state = "f_rstt";          // Lamp flag "restore state"
static const char* TCONST_fcfg_gpio = "/gpio.json";
static const char* TCONST_fcfg_ledstrip = "/ledstrip.json";
static const char* TCONST_fileName2 = "fileName2";
static const char* TCONST_fileName = "fileName";
static const char* TCONST_fill = "fill";
static const char* TCONST_flags = "flags";
static const char* TCONST_force = "force";
static const char* TCONST_gbright = "gbright";
static const char* TCONST_GBR = "GBR";
static const char* TCONST_GlobBRI = "GlobBRI";
static const char* TCONST_height = "height";
static const char* TCONST_hflip = "hflip";
static const char* TCONST_hold = "hold";
static const char* TCONST_Host = "Host";
static const char* TCONST_Ip = "Ip";
static const char* TCONST_isClearing = "isClearing";
static const char* TCONST_isFaderON = "isFaderON";
static const char* TCONST_isOnMP3 = "isOnMP3";
static const char* TCONST_isPlayTime = "isPlayTime";
static const char* TCONST_isShowOff = "isShowOff";
static const char* TCONST_isStreamOn = "isStreamOn";
static const char* TCONST_lamptext = "lamptext";
static const char* TCONST_lamp_config = "lamp_config";
static const char* TCONST_lcurve = "lcurve";
static const char* TCONST_limitAlarmVolume = "limitAlarmVolume";
static const char* TCONST_load = "load";
static const char* TCONST_lV = "lV";
static const char* TCONST_Mac = "Mac";
static const char* TCONST_main = "main";
static const char* TCONST_makeidx = "makeidx";
static const char* TCONST_mapping = "mapping";
static const char* TCONST_Memory = "Memory";
static const char* TCONST_micNoise = "micNoise";
static const char* TCONST_micnRdcLvl = "micnRdcLvl";
static const char* TCONST_micScale = "micScale";
static const char* TCONST_Mic = "Mic";
static const char* TCONST_mic_cal = "mic_cal";
static const char* TCONST_MIRR_H = "MIRR_H";
static const char* TCONST_MIRR_V = "MIRR_V";
static const char* TCONST_Mode = "Mode";
static const char* TCONST_mode = "mode";
static const char* TCONST_mosfet_gpio = "fet_gpio";             // MOSFET gpio
static const char* TCONST_mosfet_ll = "fet_ll";                // MOSFET logic level
static const char* TCONST_mp3count = "mp3count";
static const char* TCONST_mp3volume = "mp3volume";
static const char* TCONST_mp3rx = "mp3rx";
static const char* TCONST_mp3tx = "mp3tx";
static const char* TCONST_mp3_n5 = "mp3_n5";
static const char* TCONST_mp3_p5 = "mp3_p5";
static const char* TCONST_MQTTTopic = "MQTTTopic";
static const char* TCONST_msg = "msg";
static const char* TCONST_mx_gpio = "mx_gpio";
static const char* TCONST_nofade = "nofade";
static const char* TCONST_Normal = "Normal";
static const char* TCONST_numInList = "numInList";
static const char* TCONST_ny_period = "ny_period";
static const char* TCONST_ny_unix = "ny_unix";
static const char* TCONST_onetime = "onetime";
static const char* TCONST_ONflag = "ONflag";
static const char* TCONST_on = "on";
static const char* TCONST_opt_pass = "opt_pass";
static const char* TCONST_OTA = "OTA";
static const char* TCONST_Other = "Other";
static const char* TCONST_pFS = "pFS";
static const char* TCONST_PINB = "PINB"; // пин кнопки
static const char* TCONST_pin = "pin";
static const char* TCONST_playEffect = "playEffect";
static const char* TCONST_playMP3 = "playMP3";
static const char* TCONST_playName = "playName";
static const char* TCONST_playTime = "playTime";
static const char* TCONST_pMem = "pMem";
static const char* TCONST_pRSSI = "pRSSI";
static const char* TCONST_pTemp = "pTemp";
static const char* TCONST_pTime = "pTime";
static const char* TCONST_pUptime = "pUptime";
static const char* TCONST_repeat = "repeat";
static const char* TCONST_RGB = "RGB";
static const char* TCONST_RSSI = "RSSI";
static const char* TCONST_save = "save";
static const char* TCONST_scale = "scale";
static const char* TCONST_settings = "settings";
static const char* TCONST_settings_ledstrip = "set_ledstrip";
static const char* TCONST_settings_mic = "settings_mic";
static const char* TCONST_settings_mp3 = "settings_mp3";
static const char* TCONST_settings_wifi = "settings_wifi";
static const char* TCONST_set_gpio = "s_gpio";                    // set gpio action
static const char* TCONST_set_butt = "set_butt";
static const char* TCONST_set_effect = "set_effect";
static const char* TCONST_set_enc = "set_enc";
static const char* TCONST_set_event = "set_event";
static const char* TCONST_set_mic = "set_mic";
static const char* TCONST_set_mp3 = "set_mp3";
static const char* TCONST_set_mqtt = "set_mqtt";
static const char* TCONST_set_opt_pass = "set_opt_pass";
static const char* TCONST_set_other = "set_other";
static const char* TCONST_sh_page = "sh_page";                    // show_page action for webui page selector
static const char* TCONST_showName = "showName";
static const char* TCONST_show_button = "show_button";
static const char* TCONST_show_butt = "show_butt";
static const char* TCONST_show_event = "show_event";
static const char* TCONST_show_flags = "show_flags";
static const char* TCONST_show_mp3 = "show_mp3";
static const char* TCONST_snake = "snake";
static const char* TCONST_soundfile = "soundfile";
static const char* TCONST_spdcf = "spdcf";
static const char* TCONST_speed = "speed";
static const char* TCONST_state = "state";
static const char* TCONST_STA = "STA";
static const char* TCONST_stopat = "stopat";
static const char* TCONST_streaming = "streaming";
static const char* TCONST_stream_type = "stream_type";
static const char* TCONST_sT = "sT";
static const char* TCONST_syslampFlags = "syslampFlags";
static const char* TCONST_sysSettings = "sysSettings";
static const char* TCONST_textsend = "textsend";
static const char* TCONST_text_config = "text_config";
static const char* TCONST_Time = "Time";
static const char* TCONST_tm24 = "tm24";
static const char* TCONST_tm_clk = "tmclk";
static const char* TCONST_tm_dio = "tmdio";
static const char* TCONST_tmBrightOff = "tmBrightOff";
static const char* TCONST_tmBrightOn = "tmBrightOn";
static const char* TCONST_tmBright = "tmBright";
static const char* TCONST_tmEvent = "tmEvent";
static const char* TCONST_tmZero = "tmZero";
static const char* TCONST_txtBfade = "txtBfade";
static const char* TCONST_txtColor = "txtColor";
static const char* TCONST_txtOf = "txtOf";
static const char* TCONST_txtSpeed = "txtSpeed";
static const char* TCONST_Universe = "Universe";
static const char* TCONST_Uptime = "Uptime";
static const char* TCONST_value = "value";
static const char* TCONST_vertical = "vertical";
static const char* TCONST_Version = "Version";
static const char* TCONST_vflip = "vflip";
static const char* TCONST_wcpass = "wcpass";
static const char* TCONST_White = "White";
static const char* TCONST_width = "width";
static const char* TCONST_XLOAD = "xload";
static const char* TCONST__5f9ea0 = "#5f9ea0";
static const char* TCONST__708090 = "#708090";
static const char* TCONST__backup_btn_ = "/backup/btn/";
static const char* TCONST__backup_evn_ = "/backup/evn/";
static const char* TCONST__backup_glb_ = "/backup/glb/";
static const char* TCONST__backup_idx = "/backup/idx";
static const char* TCONST__backup_idx_ = "/backup/idx/";
static const char* TCONST__demo = "demo";
static const char* TCONST__ffffff = "#ffffff";
static const char* TCONST__tmplist_tmp = "/tmplist.tmp";
static const char* TCONST__tmpqlist_tmp = "/tmpqlist.tmp";

/** набор служебных текстовых констант (HTTP/MQTT запросы) */
static const char* CMD_ON = "ON";                    // Без параметров - возвращает 1/0 в зависимости вкл/выкл лампа, принимает параметр - 1/0 (вкл/выкл лампу)
static const char* CMD_OFF = "OFF";                  // Без параметров - возвращает 1/0 в зависимости выкл/вкл лампа, принимает параметр - 1/0 (выкл/вкл лампу)
static const char* CMD_G_BRIGHT = "G_BRIGHT";        // Без параметров - возвращает 1/0 в зависимости вкл/выкл глобальная яркость, принимает параметр - 1/0 (вкл/выкл глобальная яркость)
static const char* CMD_G_BRTPCT = "G_BRTPCT";        // Без параметров - возвращает общую яркость в процентах, принимает параметр - 0-100 выставить общую яркость в процентах
static const char* CMD_DEMO = "DEMO";                // Без параметров - возвращает 1/0 в зависимости вкл/выкл глобальная яркость, принимает параметр - 1/0 (вкл/выкл глобальная яркость)
static const char* CMD_PLAYER = "PLAYER";            // Без параметров - возвращает 1/0 в зависимости вкл/выкл плеер, принимает параметр - 1/0 (вкл/выкл плеер)
static const char* CMD_MP3_SOUND = "MP3_SOUND";      // Без параметров - возвращает 1/0 в зависимости вкл/выкл проигрывание MP3, принимает параметр - 1/0 (вкл/выкл проигрывание MP3)
static const char* CMD_MP3_PREV = "MP3_PREV";        // Без параметров - переключает трек на 1 назад, принимает числовой параметр, на сколько треков вернуть назад
static const char* CMD_MP3_NEXT = "MP3_NEXT";        // Без параметров - переключает трек на 1 назад, принимает числовой параметр, на сколько треков вернуть назад
static const char* CMD_MP3_VOLUME = "MP3_VOL";       // принимает числовой параметр - установить громкость mp3 плеера
static const char* CMD_MIC = "MIC";                  // Без параметров - возвращает 1/0 в зависимости вкл/выкл микрофон, принимает параметр - 1/0 (вкл/выкл микрофон)
static const char* CMD_EFFECT = "EFFECT";            // Без параметров - возвращает номер текущего эффекта, принимает числовой параметр - включить заданный эффект
static const char* CMD_WARNING = "WARNING";          // Без параметров - мигает желтым 5 раз (1 раз в сек), принимает параметры /cmd?warning=[16777215,5000,500,1] - неблокирующий вывод мигалки поверх эффекта (выдача предупреждений), первое число - цвет, второе - полный период, третье - полупериод мигания, четвертое - тип уведомления (0 - цвет, 1-2 - цвет и счетчик, 3 - счетчик)
static const char* CMD_EFF_CONFIG = "EFF_CONFIG";    // Без параметров - возвращает ВСЕ настройки текущего эффекта, с параметрами - не реализовано пока
static const char* CMD_CONTROL = "CONTROL";          // Только с параметрами - принимает числовой параметр (номер контрола) и возвращает его текущие настройки, также принимает массив /cmd?control=[N,val] где - N - номер контрола, val - нужное значение
static const char* CMD_RGB = "RGB";                  // RGB = r,g,b т.е. к примеру для красного 255,0,0
static const char* CMD_LIST = "LIST";                // Без параметров - возвращает полный список эффектов (их номера)
static const char* CMD_SHOWLIST = "SHOWLIST";        // Без параметров - возвращает список отображаемых эффектов (их номера)
static const char* CMD_DEMOLIST = "DEMOLIST";        // Без параметров - возвращает список отображаемых эффектов (их номера) в DEMO режиме
static const char* CMD_EFF_NAME = "EFF_NAME";        // Без параметров - возвращает из конфига имя текущего эффекта, принимает числовой параметр (номер эффекта) и возвращает имя этого эффекта
static const char* CMD_EFF_ONAME = "EFF_ONAME";      // Без параметров - возвращает из внутренней памяти имя текущего эффекта, принимает числовой параметр (номер эффекта) и возвращает имя этого эффекта
static const char* CMD_MOVE_NEXT = "MOVE_NEXT";      // Без параметров - переключает на следующий эффект
static const char* CMD_MOVE_PREV = "MOVE_PREV";      // Без параметров - переключает на предыдущий эффект
static const char* CMD_MOVE_RND = "MOVE_RND";        // Без параметров - переключает на рандомный эффект
static const char* CMD_REBOOT = "REBOOT";            // Без параметров - перезагружает лампу
static const char* CMD_ALARM = "ALARM";              // Без параметров - возвращает 1/0 в зависимости включен ли сейчас будильник рассвет, принимает параметры "cmd?alarm={alarmP=N,alarmT=N,msg="Message",lV=N, afS=N, sT=N}", где alarmP длительность рассвета, alarmT - светить после рассвета, msg - сообщение, lV - уровень громкости будильника, afS - стандартная ли мелодия будильника, sT - мелодия будильника (от 0 до 7), все комманды указывать не обязательно
static const char* CMD_MATRIX = "MATRIX";            // Возвращает размер матрицы в формате [X, Y]
static const char* CMD_MSG = "MSG";                  // Только с параметрами - выводит сообщение на лампу
static const char* CMD_DRAW = "DRAW";                // Только с параметрами =[цвет,X,Y] - закрашивает пиксель указанным цветом (если включено рисование)
static const char* CMD_INC_CONTROL = "INC_CONTROL";  // Только с параметрами =[N,val] - увеличивает\уменьшает контрол N на значение val
static const char* CMD_FILL_MATRIX = "FILL_MATRIX";  // Только с параметрами - закрашивает матрицу указанным цветом (если включено рисование)
static const char* CMD_AUX_ON = "AUX_ON";            // Включает AUX пин
static const char* CMD_AUX_OFF = "AUX_OFF";          // Выключает AUX пин
static const char* CMD_AUX_TOGGLE = "AUX_TOGGLE";    // Переключает AUX пин
static const char* CMD_DRAWING = "DRAWING";          // Без параметров - возвращает 1/0 в зависимости вкл/выкл рисование, принимает параметр - 1/0 (вкл/выкл рисование)


