#pragma once
/** набор служебных текстовых констант (не для локализации)
 */
static const char TCONST_0000[] PROGMEM = "effects";
static const char TCONST_0001[] PROGMEM = "pTime";
static const char TCONST_0002[] PROGMEM = "pMem";
static const char TCONST_0003[] PROGMEM = "lamptext";
static const char TCONST_0004[] PROGMEM = "settings";
static const char TCONST_0005[] PROGMEM = "set_effect";
static const char TCONST_0006[] PROGMEM = "eff_sel";
static const char TCONST_0007[] PROGMEM = "eff_fav";
static const char TCONST_0008[] PROGMEM = "encoder";
static const char TCONST_0009[] PROGMEM = "copy";
static const char TCONST_000A[] PROGMEM = "del*";
static const char TCONST_000B[] PROGMEM = "makeidx";
static const char TCONST_000C[] PROGMEM = "set_enc";
static const char TCONST_000D[] PROGMEM = "black";
static const char TCONST_000E[] PROGMEM = "AUX";
static const char TCONST_000F[] PROGMEM = "effects_config";
static const char TCONST_0010[] PROGMEM = "effListConf";
static const char TCONST_effects_param[] PROGMEM = "effects_param";
static const char TCONST_0012[] PROGMEM = "bright";
static const char TCONST_0013[] PROGMEM = "speed";
static const char TCONST_0014[] PROGMEM = "scale";
static const char TCONST_dynCtrl[] PROGMEM = "dynCtrl";
static const char TCONST_0016[] PROGMEM = "effListMain";
static const char TCONST_0017[] PROGMEM = "nofade";
static const char TCONST_0018[] PROGMEM = "GlobBRI";
static const char TCONST_0019[] PROGMEM = "flags";
static const char TCONST_001A[] PROGMEM = "ONflag";
static const char TCONST_001B[] PROGMEM = "Demo";
static const char TCONST_001C[] PROGMEM = "GBR";
static const char TCONST_001D[] PROGMEM = "Events";
static const char TCONST_001E[] PROGMEM = "Mic";
static const char TCONST_001F[] PROGMEM = "Btn";
static const char TCONST_0020[] PROGMEM = "show_flags";
static const char TCONST_0021[] PROGMEM = "mode";
static const char TCONST_0022[] PROGMEM = "eff_prev";
static const char TCONST_0023[] PROGMEM = "eff_next";
static const char TCONST_0024[] PROGMEM = "#708090";
static const char TCONST_0025[] PROGMEM = "#5f9ea0";
static const char TCONST_0026[] PROGMEM = "DTimer";
static const char TCONST_0027[] PROGMEM = "OTA";
static const char TCONST_0028[] PROGMEM = "lamp_config";
static const char TCONST_0029[] PROGMEM = "edit_lamp_config";
static const char TCONST_002A[] PROGMEM = "fileName";
static const char TCONST_002B[] PROGMEM = "/backup/idx";
static const char TCONST_002C[] PROGMEM = "/backup/idx/";
static const char TCONST_002D[] PROGMEM = "load";
static const char TCONST_002E[] PROGMEM = "save";
static const char TCONST_002F[] PROGMEM = "ds18b20";
static const char TCONST_0030[] PROGMEM = "add_lamp_config";
static const char TCONST_0031[] PROGMEM = "/backup/glb/";
static const char TCONST_0032[] PROGMEM = "/backup/evn/";
static const char TCONST_0033[] PROGMEM = "/backup/btn/";
static const char TCONST_0034[] PROGMEM = "textsend";
static const char TCONST_0035[] PROGMEM = "msg";
static const char TCONST_0036[] PROGMEM = "txtColor";
static const char TCONST_0037[] PROGMEM = "settings_mic";
static const char TCONST_0038[] PROGMEM = "set_mic";
static const char TCONST_0039[] PROGMEM = "micScale";
static const char TCONST_003A[] PROGMEM = "micNoise";
static const char TCONST_003B[] PROGMEM = "micnRdcLvl";
static const char TCONST_003C[] PROGMEM = "mic_cal";
static const char TCONST_003D[] PROGMEM = "settings_wifi";
static const char TCONST_003E[] PROGMEM = "pTemp";
static const char TCONST_003F[] PROGMEM = "EncVG";
static const char TCONST_0040[] PROGMEM = "EncVGCol";
static const char TCONST_0041[] PROGMEM = "wcpass";
static const char TCONST_0042[] PROGMEM = "encTxtCol";
static const char TCONST_0043[] PROGMEM = "encTxtDel";
static const char TCONST_0044[] PROGMEM = "streaming";
static const char TCONST_0045[] PROGMEM = "set_mqtt";
static const char TCONST_0046[] PROGMEM = "isStreamOn";
static const char TCONST_0047[] PROGMEM = "stream_type";
static const char TCONST_0048[] PROGMEM = "isShowOff";
static const char TCONST_0049[] PROGMEM = "direct";
static const char TCONST_004A[] PROGMEM = "mapping";
static const char TCONST_004B[] PROGMEM = "set_other";
static const char TCONST_004C[] PROGMEM = "MIRR_H";
static const char TCONST_004D[] PROGMEM = "MIRR_V";
static const char TCONST_004E[] PROGMEM = "isFaderON";
static const char TCONST_004F[] PROGMEM = "DRand";
static const char TCONST_0050[] PROGMEM = "effSort";
static const char TCONST_0051[] PROGMEM = "txtSpeed";
static const char TCONST_0052[] PROGMEM = "txtOf";
static const char TCONST_0053[] PROGMEM = "spdcf";
static const char TCONST_0054[] PROGMEM = "ny_period";
static const char TCONST_0055[] PROGMEM = "ny_unix";
static const char TCONST_0056[] PROGMEM = "isPlayTime";
static const char TCONST_005B[] PROGMEM = "blue";
static const char TCONST_005C[] PROGMEM = "show_event";
static const char TCONST_005D[] PROGMEM = "event_conf";
static const char TCONST_005E[] PROGMEM = "eventList";
static const char TCONST_005F[] PROGMEM = "edit";
static const char TCONST_0060[] PROGMEM = "enabled";
static const char TCONST_0061[] PROGMEM = "d1";
static const char TCONST_0062[] PROGMEM = "d2";
static const char TCONST_0063[] PROGMEM = "d3";
static const char TCONST_0064[] PROGMEM = "d4";
static const char TCONST_0065[] PROGMEM = "d5";
static const char TCONST_0066[] PROGMEM = "d6";
static const char TCONST_0067[] PROGMEM = "d7";
static const char TCONST_0068[] PROGMEM = "evList";
static const char TCONST_0069[] PROGMEM = "repeat";
static const char TCONST_006A[] PROGMEM = "stopat";
static const char TCONST_006B[] PROGMEM = "tmEvent";
static const char TCONST_006C[] PROGMEM = "set_event";
static const char TCONST_006D[] PROGMEM = "show_button";
static const char TCONST_006E[] PROGMEM = "butt_conf";
static const char TCONST_006F[] PROGMEM = "buttList";
static const char TCONST_0070[] PROGMEM = "on";
static const char TCONST_0071[] PROGMEM = "hold";
static const char TCONST_0072[] PROGMEM = "onetime";
static const char TCONST_0073[] PROGMEM = "clicks";
static const char TCONST_0074[] PROGMEM = "bactList";
static const char TCONST_0075[] PROGMEM = "set_butt";
static const char TCONST_0076[] PROGMEM = "show_butt";
static const char TCONST_0077[] PROGMEM = "Universe";
static const char TCONST_0079[] PROGMEM = "show_mic";
static const char TCONST_007A[] PROGMEM = "show_other";
static const char TCONST_007C[] PROGMEM = "#ffffff";
static const char TCONST_007D[] PROGMEM = "1609459200";
static const char TCONST_007E[] PROGMEM = "main";
static const char TCONST_007F[] PROGMEM = "dynCtrl*";
static const char TCONST_0080[] PROGMEM = "STA";
static const char TCONST_0081[] PROGMEM = "/tmpqlist.tmp";
static const char TCONST_fquicklist[] PROGMEM = "/fquicklist.json";
static const char TCONST_fslowlist[] PROGMEM = "/fslowlist.json";
static const char TCONST_slowlist[] PROGMEM = "/slowlist.json";
static const char TCONST_0085[] PROGMEM = "/tmplist.tmp";
static const char TCONST_quicklist[] PROGMEM = "/quicklist.json";
static const char TCONST_008B[] PROGMEM = "embui/pub/";
static const char TCONST_008C[] PROGMEM = "pin";
static const char TCONST_008D[] PROGMEM = "act";
static const char TCONST_008E[] PROGMEM = "isClearing";
static const char TCONST_008F[] PROGMEM = "pUptime";
static const char TCONST_0090[] PROGMEM = "numInList";
static const char TCONST_0091[] PROGMEM = "effHasMic";
static const char TCONST_0092[] PROGMEM = "effname";
static const char TCONST_0093[] PROGMEM = "set_opt_pass";
static const char TCONST_0094[] PROGMEM = "syslampFlags";
static const char TCONST_0095[] PROGMEM = "debug";
static const char TCONST_0096[] PROGMEM = "isShowSysMenu";
static const char TCONST_0097[] PROGMEM = "PINB"; // пин кнопки
static const char TCONST_0098[] PROGMEM = "CLmt"; // лимит тока
static const char TCONST_0099[] PROGMEM = "sysSettings";
static const char TCONST_009A[] PROGMEM = "ESPsysSettings";
static const char TCONST_009B[] PROGMEM = "PINMP3RX";
static const char TCONST_009C[] PROGMEM = "PINMP3TX";
static const char TCONST_009D[] PROGMEM = "isOnMP3";
static const char TCONST_009E[] PROGMEM = "showName";
static const char TCONST_009F[] PROGMEM = "show_mp3";
static const char TCONST_00A0[] PROGMEM = "set_mp3";
static const char TCONST_00A1[] PROGMEM = "settings_mp3";
static const char TCONST_00A2[] PROGMEM = "mp3volume";
static const char TCONST_00A3[] PROGMEM = "playTime";
static const char TCONST_00A4[] PROGMEM = "playName";
static const char TCONST_00A5[] PROGMEM = "playEffect";
static const char TCONST_00A6[] PROGMEM = "alarmSound";
static const char TCONST_00A7[] PROGMEM = "eqSetings";
static const char TCONST_00A8[] PROGMEM = "playMP3";
static const char TCONST_00A9[] PROGMEM = "mp3count";
static const char TCONST_00AA[] PROGMEM = "demo";
static const char TCONST_00AB[] PROGMEM = "soundfile";
static const char TCONST_00AC[] PROGMEM = "embui/get/";
static const char TCONST_00AD[] PROGMEM = "state";
static const char TCONST_00AE[] PROGMEM = "eff_config";
static const char TCONST_00AF[] PROGMEM = "limitAlarmVolume";
static const char TCONST_00B0[] PROGMEM = "delfromlist";
static const char TCONST_00B1[] PROGMEM = "delall";
static const char TCONST_00B2[] PROGMEM = "delCfg";
static const char TCONST_00B3[] PROGMEM = "orange";
static const char TCONST_00B4[] PROGMEM = "gbright";
static const char TCONST_00B5[] PROGMEM = "bparam";
static const char TCONST_00B6[] PROGMEM = "delete";
static const char TCONST_00B8[] PROGMEM = "opt_pass";
static const char TCONST_00B9[] PROGMEM = "text_config";
static const char TCONST_00BA[] PROGMEM = "edit_text_config";
static const char TCONST_00BB[] PROGMEM = "alarmP";
static const char TCONST_00BC[] PROGMEM = "alarmT";
static const char TCONST_00BD[] PROGMEM = "alarmPT";
static const char TCONST_00C0[] PROGMEM = "mp3_p5";
static const char TCONST_00C1[] PROGMEM = "mp3_n5";
static const char TCONST_00C2[] PROGMEM = "pFS";
static const char TCONST_00C3[] PROGMEM = "txtBfade";
static const char TCONST_00C4[] PROGMEM = "drawbuff";
static const char TCONST_00C8[] PROGMEM = "drawing";
static const char TCONST_00C9[] PROGMEM = "drawing_ctrl";
static const char TCONST_00CA[] PROGMEM = "drawing_ctrl*";
static const char TCONST_00CB[] PROGMEM = "blabel";
static const char TCONST_00CC[] PROGMEM = "height";
static const char TCONST_00CD[] PROGMEM = "width";
static const char TCONST_00CE[] PROGMEM = "pRSSI";
static const char TCONST_00CF[] PROGMEM = "fileName2";
static const char TCONST_00D0[] PROGMEM = "control";
static const char TCONST_00D1[] PROGMEM = "afS";
static const char TCONST_00D2[] PROGMEM = "lV";
static const char TCONST_00D3[] PROGMEM = "sT";
static const char TCONST_00D5[] PROGMEM = "force";
static const char TCONST_00D7[] PROGMEM = "tmBright";
static const char TCONST_00D8[] PROGMEM = "tmBrightOn";
static const char TCONST_00D9[] PROGMEM = "tmBrightOff";
static const char TCONST_00DA[] PROGMEM = "tm24";
static const char TCONST_00DB[] PROGMEM = "tmZero";
static const char TCONST_00DC[] PROGMEM = "drawClear";
static const char TCONST_00DD[] PROGMEM = "Mode";
static const char TCONST_00DE[] PROGMEM = "Time";
static const char TCONST_00DF[] PROGMEM = "Memory";
static const char TCONST_00E0[] PROGMEM = "Uptime";
static const char TCONST_00E1[] PROGMEM = "RSSI";
static const char TCONST_00E2[] PROGMEM = "Ip";
static const char TCONST_00E3[] PROGMEM = "Mac";
static const char TCONST_00E4[] PROGMEM = "Host";
static const char TCONST_00E5[] PROGMEM = "Version";
static const char TCONST_00E6[] PROGMEM = "MQTTTopic";
static const char TCONST_00E7[] PROGMEM = "embui/";
static const char TCONST_00E8[] PROGMEM = "Normal";
static const char TCONST_00E9[] PROGMEM = "Alarm";
static const char TCONST_00EA[] PROGMEM = "Demo";
static const char TCONST_00EB[] PROGMEM = "RGB";
static const char TCONST_00EC[] PROGMEM = "White";
static const char TCONST_00ED[] PROGMEM = "Other";


/** набор служебных текстовых констант (HTTP/MQTT запросы)
 */

static const char CMD_ON[] PROGMEM = "ON";                    // Без параметров - возвращает 1/0 в зависимости вкл/выкл лампа, принимает параметр - 1/0 (вкл/выкл лампу)
static const char CMD_OFF[] PROGMEM = "OFF";                  // Без параметров - возвращает 1/0 в зависимости выкл/вкл лампа, принимает параметр - 1/0 (выкл/вкл лампу)
static const char CMD_G_BRIGHT[] PROGMEM = "G_BRIGHT";        // Без параметров - возвращает 1/0 в зависимости вкл/выкл глобальная яркость, принимает параметр - 1/0 (вкл/выкл глобальная яркость)
static const char CMD_DEMO[] PROGMEM = "DEMO";                // Без параметров - возвращает 1/0 в зависимости вкл/выкл глобальная яркость, принимает параметр - 1/0 (вкл/выкл глобальная яркость)
static const char CMD_PLAYER[] PROGMEM = "PLAYER";            // Без параметров - возвращает 1/0 в зависимости вкл/выкл плеер, принимает параметр - 1/0 (вкл/выкл плеер)
static const char CMD_MP3_SOUND[] PROGMEM = "MP3_SOUND";      // Без параметров - возвращает 1/0 в зависимости вкл/выкл проигрывание MP3, принимает параметр - 1/0 (вкл/выкл проигрывание MP3)
static const char CMD_MP3_PREV[] PROGMEM = "MP3_PREV";        // Без параметров - переключает трек на 1 назад, принимает числовой параметр, на сколько треков вернуть назад
static const char CMD_MP3_NEXT[] PROGMEM = "MP3_NEXT";        // Без параметров - переключает трек на 1 назад, принимает числовой параметр, на сколько треков вернуть назад
static const char CMD_MP3_VOLUME[] PROGMEM = "MP3_VOL";       // принимает числовой параметр - установить громкость mp3 плеера
static const char CMD_MIC[] PROGMEM = "MIC";                  // Без параметров - возвращает 1/0 в зависимости вкл/выкл микрофон, принимает параметр - 1/0 (вкл/выкл микрофон)
static const char CMD_EFFECT[] PROGMEM = "EFFECT";            // Без параметров - возвращает номер текущего эффекта, принимает числовой параметр - включить заданный эффект
static const char CMD_WARNING[] PROGMEM = "WARNING";          // Без параметров - мигает желтым 5 раз (1 раз в сек), принимает параметры /cmd?warning=[16777215,5000,500,1] - неблокирующий вывод мигалки поверх эффекта (выдача предупреждений), первое число - цвет, второе - полный период, третье - полупериод мигания, четвертое - тип уведомления (0 - цвет, 1-2 - цвет и счетчик, 3 - счетчик)
static const char CMD_EFF_CONFIG[] PROGMEM = "EFF_CONFIG";    // Без параметров - возвращает ВСЕ настройки текущего эффекта, с параметрами - не реализовано пока
static const char CMD_CONTROL[] PROGMEM = "CONTROL";          // Только с параметрами - принимает числовой параметр (номер контрола) и возвращает его текущие настройки, также принимает массив /cmd?control=[N,val] где - N - номер контрола, val - нужное значение
static const char CMD_RGB[] PROGMEM = "RGB";                  // RGB = r,g,b т.е. к примеру для красного 255,0,0
static const char CMD_LIST[] PROGMEM = "LIST";                // Без параметров - возвращает полный список эффектов (их номера)
static const char CMD_SHOWLIST[] PROGMEM = "SHOWLIST";        // Без параметров - возвращает список отображаемых эффектов (их номера)
static const char CMD_DEMOLIST[] PROGMEM = "DEMOLIST";        // Без параметров - возвращает список отображаемых эффектов (их номера) в DEMO режиме
static const char CMD_EFF_NAME[] PROGMEM = "EFF_NAME";        // Без параметров - возвращает из конфига имя текущего эффекта, принимает числовой параметр (номер эффекта) и возвращает имя этого эффекта
static const char CMD_EFF_ONAME[] PROGMEM = "EFF_ONAME";      // Без параметров - возвращает из внутренней памяти имя текущего эффекта, принимает числовой параметр (номер эффекта) и возвращает имя этого эффекта
static const char CMD_MOVE_NEXT[] PROGMEM = "MOVE_NEXT";      // Без параметров - переключает на следующий эффект
static const char CMD_MOVE_PREV[] PROGMEM = "MOVE_PREV";      // Без параметров - переключает на предыдущий эффект
static const char CMD_MOVE_RND[] PROGMEM = "MOVE_RND";        // Без параметров - переключает на рандомный эффект
static const char CMD_REBOOT[] PROGMEM = "REBOOT";            // Без параметров - перезагружает лампу
static const char CMD_ALARM[] PROGMEM = "ALARM";              // Без параметров - возвращает 1/0 в зависимости включен ли сейчас будильник рассвет, принимает параметры "cmd?alarm={alarmP=N,alarmT=N,msg="Message",lV=N, afS=N, sT=N}", где alarmP длительность рассвета, alarmT - светить после рассвета, msg - сообщение, lV - уровень громкости будильника, afS - стандартная ли мелодия будильника, sT - мелодия будильника (от 0 до 7), все комманды указывать не обязательно
static const char CMD_MATRIX[] PROGMEM = "MATRIX";            // Возвращает размер матрицы в формате [X, Y]
static const char CMD_MSG[] PROGMEM = "MSG";                  // Только с параметрами - выводит сообщение на лампу
static const char CMD_DRAW[] PROGMEM = "DRAW";                // Только с параметрами =[цвет,X,Y] - закрашивает пиксель указанным цветом (если включено рисование)
static const char CMD_INC_CONTROL[] PROGMEM = "INC_CONTROL";  // Только с параметрами =[N,val] - увеличивает\уменьшает контрол N на значение val
static const char CMD_FILL_MATRIX[] PROGMEM = "FILL_MATRIX";  // Только с параметрами - закрашивает матрицу указанным цветом (если включено рисование)
static const char CMD_AUX_ON[] PROGMEM = "AUX_ON";            // Включает AUX пин
static const char CMD_AUX_OFF[] PROGMEM = "AUX_OFF";          // Выключает AUX пин
static const char CMD_AUX_TOGGLE[] PROGMEM = "AUX_TOGGLE";    // Переключает AUX пин
static const char CMD_DRAWING[] PROGMEM = "DRAWING";          // Без параметров - возвращает 1/0 в зависимости вкл/выкл рисование, принимает параметр - 1/0 (вкл/выкл рисование)


